# ----------------------------------------------------------------------------
# Name:         openAttachment.py
# Description:  python script skeleton, to open email attachment.
# Author:       Spencer Brown
# URL:          https://github.com/spence-rat/pywin-auto-open-email-attachment
# Date:         01/14/2022
# ----------------------------------------------------------------------------

from pywinauto import Application, Desktop
import time
#starts the application you are wanting to automate
start_program = "<path to program>"

app = Application(backend="uia").start(start_program)
#example
app = Application(backend="uia").start(r'C:\Program Files\Microsoft Office\root\Office16\OUTLOOK')
##gives time for application to fully load before windows are available to pywinauto##
time.sleep(10)

#----------------------------Define your application main dialog window--------
#you can see what windows are available to you throughout this process by running:
#print app.windows()
main_dlg = app[name_of_window]
#example: main_dlg = app['name_of_main_window']
#example: main_dlg = app['Inbox - John.Doe@email.com - Outlook']
##could be possible to use regex here -> app.window(title_re="*-Outlook")

#---------------------------Finding Control Identifiers----------------------
#From here, you will need to find the 'control identifiers' or the 'handle' on the window in question
#to do this call the print_control_identifiers method 
#example: main_dlg.print_control_identifiers()
#example: main_dlg.print_control_identifiers(filename="path_to_file"), to output into a log file. 

#-----------------------------Identify a particular email----------------------
email = main_dlg.child_window(control_identifier_of_element)
#example = main_dlg.child_window(title="title", auto_id="4306", control_type="Pane")
#example = main_dlg['identifier']
#click to open new email window
email.click_input(double=True)
time.sleep(10)

#-----------------------------Reference the new open window--------------------
#to identifiy all windows, including the newly opened one, run print(app.windows())
open_dlg = app['name_of_newly_opened_window']

#-----------------------------Define the attachments part of the open email----
#run attachments.print_control_identifers() to see available controls
#in an example of outputs having the same name, you can call the unique handle generated by pywinauto
#in this case it was 'Button1' to open the attachment
attachments = open_dlg.child_window('control_identifier_on_email_for_the_attachment')
#or attachments[control_identifier].method()
#double click the attachment
attachments.Button1.click_input(double=True)
